package org.skyline.common.message;

/**
 * @author Sean Liu
 * @date 2019-07-13
 */
public enum MessageType {

  /**
   * message generated by YarnApplicationFetcher
   */
  APPLICATION_FETCH,

  /**
   * Application data fetch done, generated by FetcherDispatcher
   */
  APPLICATION_FETCH_DONE,

  /**
   * Application not finished, skip fetch application data
   */
  APPLICATION_FETCH_SKIPPED,

  /**
   * Application advisor advise done
   */
  APPLICATION_ADVISE_DONE
}
