language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - '$HOME/.m2/repository'

#before_install:
# - chmod +x gradlew

script:
  - mvn clean package -DskipTests=true

after_success:
  - mvn clean

branches:
  only:
    - dev

notifications:
  email: false