language: java
jdk:
- openjdk8
cache:
  directories:
  - "$HOME/.m2/repository"
script:
- mvn clean package -DskipTests=true
branches:
  only:
  - dev
notifications:
  email: false
deploy:
  provider: releases
  api_key:
    secure: vWHMOC+plaqZu+ywSbxn/GGHuI9ggqO6GAvkckuU5yn8LeIpc4g+S101I4iXKkzbiWpBf6l5uC0FIUcEtSFm3/4mNLyNtEqQI7nQHRIDiwjplFWE+IaK1pyY7hr3dJH6YR3ifip6MvLOGhSwT5lQQsLobZxUg0l3goW0w/VudP6TwBwA2OQGQEnIBixlWfIhl9oqEDcxgAjR/2+41prFfPiLJGFLR4nyFNujppy/h4CVEfZv4zA7NX6fjxfqgGQz6tH8LwtCig8gm/FJarXOX7ehxNqsPRbMb/3oKxIhGUMtPZu1iVHm6uhRwfiDB/It524Nw/xlGt5yDZWpZwzceZX51lXzgLPG7k0Drf+GAZ0E3ujhVr+j6MT2SgXvykQAN2hJ+Fak3eVx3+0x3uGIE0D0QZbHK3XwkLvBswUrsOHAOWx/zVrkxdfCcJOhi3WPMMq1bYVi1WwAk+Iq/zbACo4Y3sJ29q5XBs285cipkXgfai/G4Rp8qfAHZIE8O6FaEislnmQoEP8yeYa2KakgO7ZqyhFoR9EodPdrnElckS5gfEpr+CGMH04oFdugIuuhHNjnKOmSlePLFjVyzH8MJ2kp3YjSYViyuISRWyPpYSOx0BSRNP4s6b+q6tPM8CxD0e3vDPAkj22Z905B3nq59WjJwD6DtvO5As8JIN6DDMU=
  file: assembly/target/*.zip
  skip_cleanup: true
  on:
    repo: wendaoheri/skyline
    branch: dev