language: java
jdk:
- openjdk8
cache:
  directories:
  - "$HOME/.m2/repository"
script:
- mvn clean package -DskipTests=true
branches:
  only:
  - dev
notifications:
  email: false
deploy:
  provider: releases
  api_key:
    secure: QAC3OLrcNQhL6ERxJ/hzrq1mpXEUry8dMxRYHxNSnPDto4WnFpPHikANelLFd4R8yI4VXzU22pdvfAfmCVd+dLozrqQc5szM88VMc8pSc5EWpmlupRA0uDg2Fq3vMWzEuFcaJzoZP8xBoNOTbqCkdjlEJRfJhgev98Bb7JbfXZnLxIMlVrwgcHawxYzoH1sRuwuE+CuFpiCyPDRT8MArIKU5y3OCVUMq3gyvco+3msoxLirC6u7yFcpyHv636oc/M4mCny5lCbybjrXuKLsbxYhkWCxahwkhapctCqh4CgS6ndt2Rf8ZUIkEzcyDUE65QQs6TND6aDIzPBh7JFFFv8e2c+VUKZg6AGJtRPcmfR+hNZwhvCkGJ6khzRYePPptU5oImnccq2M9zA7T75h6JfgtjoE8XaZLpZYukePFpkrUGggAxqKeyEqpCqWRDhnkBHXuApxODUq+VObqNX6qT2CjDqbMFyOLCdiGY+8k/eBg8UVi9J8TBH39LD1wPL3yzXNQCIcdL1rhRl2xIxB3hmOgPAP5PcWf2t2lSe04io0FTB/WlcLMkkGYK7FF3W+gPXF6GNx7c3pKqTeTiRARf3lQ5ypMnXh6e+NGFD7PM7//0Khajny8JGMXvZE90uWrTmT9acA3oPpE6oHL98pue+Z0DgSoIey1NR5a9Z8xELQ=
  file: assembly/target/*.zip
  on:
    repo: wendaoheri/skyline
    branch: dev
