language: java

jdk:
  - openjdk8

cache:
  directories:
    - '$HOME/.m2/repository'

script:
  - mvn clean package -DskipTests=true

after_success:
  - mvn clean

branches:
  only:
    - dev

notifications:
  email: false