package org.dayu.common.message;

/**
 * @author Sean Liu
 * @date 2019-07-13
 */
public enum MessageType {

  /**
   * message generated by YarnApplicationFetcher
   */
  APPLICATION_FETCH,

  /**
   * Application data fetch done, generated by FetcherDispatcher
   */
  APPLICATION_FETCH_DONE,

  /**
   * Application advisor advise done
   */
  APPLICATION_ADVISE_DONE
}
