server:
  port: 8099
spring:
  datasource:
    url: jdbc:oracle:thin:@172.16.50.21:1537:dspdata
    username: biebqry
    password: kiop0987
    driver-class-name: oracle.jdbc.OracleDriver
    configuration:
      maximum-pool-size: 30
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  data:
    elasticsearch:
      cluster-nodes: 26.6.1.114:9300,26.6.1.115:9300,26.6.1.116:9300
      cluster-name: paic-elasticsearch-v6
  mvc:
    servlet:
      path: /
  cache:
    cache-names: job_application_log
    caffeine:
      spec:
        expireAfterWrite: 24h

http:
  maxTotal: 100 #最大连接数
  defaultMaxPerRoute: 20 #并发数
  connectTimeout: 1000 #创建连接的最长时间
  connectionRequestTimeout: 500 #从连接池中获取到连接的最长时间
  socketTimeout: 10000 #数据传输的最长时间
  staleConnectionCheckEnabled: true #提交请求前测试连接是否可用
  redirectsEnabled: false # 是否允许重定向

hadoop:
  resourceManagerAddress: http://26.6.0.31:8088

spark:
  #  historyServerAddress: http://10.17.183.85:18080
  historyServerAddress: http://localhost:18080

logging:
  level:
    root: INFO
    org.hibernate: ERROR
  file: dayu.log
  max-size: 100M
  max-history: 3

dayu:
  fetcher:
    interval_second: 60                #  fetch by started & finished time interval
    unfinished_interval_second: 1      #  unfinished application state fetch interval
  plugin:
    schedule:
      class: org.dayu.plugin.schedule.dsp.DSPSchedulePlugin
      interval_second: 60
      min_delay_second: 60              #  min time delay for fetch scheduleId after application finished
      max_delay_second: 3600            #  max time delay for fetch scheduleId after application finished