spring:
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
      cluster-name: docker-cluster
      template-file: es_template.json
  cache:
    cache-names: job_application_log
    caffeine:
      spec:
        expireAfterWrite: 24h
  activemq:
    #    broker-url: tcp://localhost:9876 # comments for starting an embedded broker
    user: admin
    password: admin
  messages:
    encoding: UTF-8
    default-lang: zh_CN
    basename: messages/messages, messages/advisors


http:
  maxTotal: 100 #最大连接数
  defaultMaxPerRoute: 20 #并发数
  connectTimeout: 1000 #创建连接的最长时间
  connectionRequestTimeout: 500 #从连接池中获取到连接的最长时间
  socketTimeout: 10000 #数据传输的最长时间
  staleConnectionCheckEnabled: true #提交请求前测试连接是否可用
  redirectsEnabled: false # 是否允许重定向

hadoop:
  resourceManagerAddress: http://10.17.183.85:8088,10.17.183.85:8092
  historyServerAddress: http://10.17.183.85:19888

spark:
  #  historyServerAddress: http://10.17.183.85:18080
  historyServerAddress: http://localhost:18080

logging:
  level:
    root: INFO
    org.hibernate: ERROR
skyline:
  fetcher:
    interval_second: 60                #  fetch by started & finished time interval
    unfinished_interval_second: 1      #  unfinished application state fetch interval
  plugin:
    schedule:
      class: org.skyline.plugin.schedule.MockSchedulePlugin
      interval_second: 60
      min_delay_second: 60              #  min time delay for fetch scheduleId after application finished
      max_delay_second: 2592000            #  max time delay for fetch scheduleId after application finished
